!SFX_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!SFX_LIC This is part of the SURFEX software governed by the CeCILL-C licence
!SFX_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!SFX_LIC for details. version 1.
SUBROUTINE ERROR_READ_SURF_NC(HREC,KRESP)
!
USE MODI_ABOR1_SFX
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
 CHARACTER(LEN=*), INTENT(IN) :: HREC
INTEGER,          INTENT(IN):: KRESP ! 1 ERROR WHEN READING
                                     ! 2 FILE DOES NOT EXIST 
                                     ! 3 VRIABLE DOES NOT EXIST
                                     ! 10 UNSUPPORTED TYPE
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
  IF (LHOOK) CALL DR_HOOK('ERROR_READ_SURF_NC',0,ZHOOK_HANDLE)
  
  IF (KRESP .EQ. 1) CALL ABOR1_SFX('READ_SURF_NC: ERROR WHEN READING '//HREC)
  IF (KRESP .EQ. 2) CALL ABOR1_SFX('READ_SURF_NC: INPUT FILE DOES NOT EXIST '//HREC)       
  IF (KRESP .EQ. 3) CALL ABOR1_SFX('READ_SURF_NC: VARIABLE DOES NOT EXIST '//HREC)
  IF (KRESP .EQ. 10) CALL ABOR1_SFX('READ_SURF_NC: UNSUPPORTED TYPE FOR VARIABLE '//HREC)

  IF (LHOOK) CALL DR_HOOK('ERROR_READ_SURF_NC',1,ZHOOK_HANDLE)

END SUBROUTINE ERROR_READ_SURF_NC
